[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@chainlink/contracts=lib/chainlink-brownie-contracts/contracts/","@openzeppelin/contracts=lib/openzeppelin-contracts/contracts"]

[invariant]
runs = 128
depth = 128
fail_on_revert = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config